### ISSUE TITLE
How do I scale?

### ISSUE THREAD

**Issue by Galthariel** [jaredbwasserman/Drift#11]
Hello,

I'm able to move any window and it's indeed saving the position between sessions with the exception of the Achievements Window however it may be because I use Overachiever.

Anyways, in the description says I can also scale the windows but I could not figure out how not even seeing the video.

Thanks in advance,

**Comment by jaredbwasserman** [comment]
Hi, @Galthariel - I downloaded Overachiever. It looks like Overachiever adds its own movement to the Achievement frame that could be conflicting with Drift.

In order to scale a frame, use the right mouse button and click and drag up or down. Scaling functions similarly to moving, but it uses the right mouse button instead of the left mouse button.

I need to update the demo to include scaling. Thanks for the pointing that out!

Let me know if you have any more questions!
