### ISSUE TITLE
Barber Shop

### ISSUE THREAD

**Issue by webdevdave** [jaredbwasserman/Drift#12]
Hey buddy, how's one of my favorite addon authors doing?! So I noticed a bug with the new patch that I wanted to make you aware of. When you go to the barbershop, the buttons on the right where you select your attributes, are like shifted down and covering the button to buy/apply the changes. Here's an image with and without Drift turned on:

https://ibb.co/x19Hfr4
https://ibb.co/bJtJPFy

Hope you can fix it soon! Thanks again!

**Comment by jaredbwasserman** [comment]
Hi, Dave! Thanks for letting me know about this bug! I'm starting to look into it.

**Comment by jaredbwasserman** [comment]
I'm unable to reproduce the bug. I tried with and without Drift, and I tried with and without ElvUI.

Do you have the latest version of Drift and ElvUI downloaded?
Have you tried reloading the interface?
Is this reproduceable on more than one character?
Could you try running "/driftreset" and seeing if that fixes the issue?

Thanks!

**Comment by webdevdave** [comment]
When I tried doing "/driftreset" it didn't fix it. But when I went into the addon's options and clicked the actual "Reset Frames" button (where it pops up a confirmation box) that fixed it! So I'm not sure if the slash command it bugged (so maybe I found a different bug?) or maybe it was just a fluke. But either way, all good now... thanks again! :)

**Comment by jaredbwasserman** [comment]
I was finally able to reproduce the issue. It turns out the "BarberShopFrame" was re-implemented to take up the whole screen in the pre-patch (the same frame only used to occupy a very small space). As a result, right-clicking and dragging anywhere while in the Barber Shop interface caused everything to scale. Once scaled up, the buttons would disappear (since it was essentially zooming in on a piece of the interface). It took me a while to find because I have scaling locked, and once I unlocked scaling the issue became apparent.

That's odd with the "/driftreset" behavior. I'm not really sure what could be causing that because they use the same function call. Does "/driftreset" usually work for you?

I just released a new version of the addon on CurseForge. In this update, I removed support for Barber Shop, which should fix the button disappearing issue (it fixed the issue for me when I did a quick test). Can you download this update and verify it solves the issue?

Thanks again for reporting this bug.

**Comment by webdevdave** [comment]
To be honest, once I had everything setup I never used the /driftreset before, so I can't say if it's worked in the past. After doing the reset yesterday all seemed to be working well, but I just updated Drift and hopped into a Barbershop again and all seems to be working well. But if anything else funky goes on I'll be sure to let you know! Thanks for being so responsive btw! 💯
