### ISSUE TITLE
Objectives Window

### ISSUE THREAD

**Issue by ellaqera-7078** [jaredbwasserman/Drift#15]
Hi, is it possible to move with Objectives Window?
prnt.sc/v1w735

**Comment by jaredbwasserman** [comment]
Hi @ellaqera-7078 - good suggestion! It's not currently possible to move the Objectives Window. I'll consider adding support for it in the future.

**Comment by jaredbwasserman** [comment]
Hi @ellaqera-7078 - I added support for the Objectives Window/Objective Tracker in the latest release of Drift (1.0.6) that can be downloaded here https://www.curseforge.com/wow/addons/drift. The Objective Tracker is turned off by default. In order to turn it on, go to Interface -> AddOns -> Drift -> Options, check the "Objective Tracker Enabled" checkbox, and click "Okay". This should reload the UI and allow you to move the Objective Tracker. Feel free to reopen this ticket if you run into any issues.

Thanks!
