### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Toetag1974** [jaredbwasserman/drift#27]
Just re-downloaded this add on today after having deleted it months ago because of the fact that after a kill, a huge brown block pops up and obscures the center of the screen directly over the player character. the block easily takes up 1/3 of the screen
![WoWScrnShot_010122_195301](https://user-images.githubusercontent.com/74637048/147863983-46b70c10-85ca-4629-800b-a37d0110d207.jpg)
Before attacking.

![WoWScrnShot_010122_195341](https://user-images.githubusercontent.com/74637048/147863998-f5ec84ff-7b0f-4972-8f1b-01e33614f389.jpg)
.After killing the mobs.

**Comment by jaredbwasserman** [comment]
Hi @Toetag1974 - Thanks for reporting this! Can you let me know what version of Drift you are running? You can get the version by running `/drift version`, and the latest version is `v1.0.21`. I suspect this bug is related to an older version of the addon because I recently put in a fix for a related issue.

**Comment by Toetag1974** [comment]
I downloaded it from WOWUP shortly before I put in this report, which lists it as v1.0.21.

**Comment by jaredbwasserman** [comment]
Thanks for the information. I am not able to reproduce the issue on my end, but it's possible Drift is not compatible with some of the other addons you have installed. What are all the addons you have installed that modify the interface?

**Comment by Toetag1974** [comment]
The add ons I have are as follows:
AdvancedInterfaceOptions, Altoholic, AskMrRobot, Auctionator, Bartender4, BattlePetBreedID, BetterVendorPrice, Breakables, BtWQuests(all of them), BuyEmAll, CollectMe, CovenantForge, CovenantMissionHelper, DataStore, DBM, Details, Elvui(already checked if it was this), GatherMate2, GSE, HandyNotes(all of them), HideTalkingHead, WyredsIcyVeinsStats, Leatrix(maps&plus), Masque, Masque Hex, MBB, MountCollector, Omen, OneClickEnchant, Pawn, PetTracker, Postal, RareScanner, Rematch, Routes, Simulationcraft, SinStats, ScrollingLootText, SoulAshTip, TellMeWhen, ToyBoxEnhanced, Train-All, VenturePlan, WorldQuestTab, WorldQuestTracker.

**Comment by jaredbwasserman** [comment]
@Toetag1974 Thank you for the list. I will investigate when I have some time.

**Comment by Toetag1974** [comment]
No problem. Hopefully you can find out the problem. I enjoyed using your add on since it was a lot easier and better than the alternatives.

**Comment by jaredbwasserman** [comment]
Can you also check if the problem happens if you disable all addons except Drift? That will help determine if it's caused by an interaction between addons.

**Comment by Toetag1974** [comment]
After disabling and re-enabling my add ons one by one, I have found that the add on that was causing the big block in the center of my screen was caused by the add on mountcollector. I have since removed it.

**Comment by jaredbwasserman** [comment]
Sounds good! Is this OK to close then?

**Comment by Toetag1974** [comment]
yeah.

**Comment by halloaloe** [comment]
I have also been having this issue with Drift. Been going on for months now. I can click thru the brown block if need be, but since I initially turned the addon off and on again, all my bags are collapsed on top of one another when the addon is on and I can't move them back to where I originally positioned them when the addon wasn't giving me problems. Yes, my version is 1.0.21. I do not have the mountcollector addon the previous person did--we have very few addons in common.
Here are the two most common errors the addon throws at me. There are variations on these, but these are most frequent:
59x FrameXML\ContainerFrame.lua:1053: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: ContainerFrame2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@FrameXML\ContainerFrame.lua"]:1053: in function `UpdateContainerFrameAnchors'
[string "@FrameXML\ContainerFrame.lua"]:206: in function `ContainerFrame_OnHide'
[string "*:OnHide"]:1: in function <[string "*:OnHide"]:1>
[string "=[C]"]: in function `Hide'
[string "@FrameXML\ContainerFrame.lua"]:140: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals:
(*temporary) = ContainerFrame2 {
 FilterIcon = <unnamed> {
 }
 PortraitButton = ContainerFrame2PortraitButton {
 }
 Portrait = ContainerFrame2Portrait {
 }
 ClickableTitleFrame = <unnamed> {
 }
 0 = <userdata>
 FilterDropDown = ContainerFrame2FilterDropDown {
 }
 size = 32
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = -41.000023
(*temporary) = 130

48x FrameXML\ContainerFrame.lua:1061: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: ContainerFrame4:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@FrameXML\ContainerFrame.lua"]:1061: in function `UpdateContainerFrameAnchors'
[string "@FrameXML\ContainerFrame.lua"]:206: in function `ContainerFrame_OnHide'
[string "*:OnHide"]:1: in function <[string "*:OnHide"]:1>
[string "=[C]"]: in function `Hide'
[string "@FrameXML\ContainerFrame.lua"]:140: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals:
(*temporary) = ContainerFrame4 {
 FilterIcon = <unnamed> {
 }
 PortraitButton = ContainerFrame4PortraitButton {
 }
 Portrait = ContainerFrame4Portrait {
 }
 ClickableTitleFrame = <unnamed> {
 }
 0 = <userdata>
 FilterDropDown = ContainerFrame4FilterDropDown {
 }
 size = 32
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = "ContainerFrame3"
(*temporary) = "TOPRIGHT"
(*temporary) = 0
(*temporary) = 0

Please help me fix this. I want to be able to see all my bags open at the same time without my error sound going off every three seconds. It's driving me bonkers.

**Comment by jaredbwasserman** [comment]
@halloaloe - Thanks for letting me know. I believe the two issues are unrelated.
For the brown block, I am not able to reproduce the issue, so it would help me to know more information. Can you disable all addons you have enabled except for Drift and see if the issue still occurs? This will help me determine if it's caused by Drift directly or for some other reason.
For the bag issue, I've done some investigation on this before. Can you go into the Drift options and disable Bags if you have it enabled? If it's not enabled, can you try enabling, clicking Okay, and then disabling, then clicking Okay again? I added code that triggers when Bags are disabled that should hopefully fix the issue you are seeing.
![WoWScrnShot_011722_004856](https://user-images.githubusercontent.com/5832654/149737577-14d0dc5e-a312-4f40-9016-59dc8d822bdd.jpg)

**Comment by halloaloe** [comment]
I disabled all addons except Drift, logged in. No brown box upon mouse over of anything (which is usually what happens), but upon Shift B to open all bags, I was immediately given this:
Message: Interface\FrameXML\ContainerFrame.lua:1053: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: ContainerFrame2:SetPoint.
Time: Mon Jan 17 02:00:16 2022
Count: 1
Stack: Interface\FrameXML\ContainerFrame.lua:1053: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: ContainerFrame2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1053: in function `UpdateContainerFrameAnchors'
[string "@Interface\FrameXML\ContainerFrame.lua"]:206: in function `ContainerFrame_OnHide'
[string "*:OnHide"]:1: in function <[string "*:OnHide"]:1>
[string "=[C]"]: in function `Hide'
[string "@Interface\FrameXML\ContainerFrame.lua"]:140: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals: (*temporary) = ContainerFrame2 {
 FilterIcon = <unnamed> {
 }
 PortraitButton = ContainerFrame2PortraitButton {
 }
 Portrait = ContainerFrame2Portrait {
 }
 ClickableTitleFrame = <unnamed> {
 }
 0 = <userdata>
 FilterDropDown = ContainerFrame2FilterDropDown {
 }
 size = 32
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = -41.000023
(*temporary) = 130

Bags still pile on top of each other. Will go into options momentarily.

**Comment by halloaloe** [comment]
Followed your instructions within Drift's options. Bags are now back to how I set them--thank you! Should I check the Bags option again before re-enabling other addons a handful at a time? Or would you like me to wait before attempting anything else?

**Comment by halloaloe** [comment]
Got brown box back upon hitting "U" then changing to reputation tab. Disabled the few addons I had turned back on, then slowly re-enabled, only for the brown box to pop up upon hitting "I" and clicking on PvP tab instead. Only addons I had turned on at the time: DBM, Drift, PetTracker and dependents, Reputation Bars, Soulshape Journal (highly doubt this is culprit, I've only had it a few days), TomCat's Tours, TomTom, Work Complete Notification, WowheadLooter, xanDurability, xanGoldMine, Z-Perl UnitFrames and dependents, Zoom. I also had Wholly enabled with the "U" box, but disabled with the "I" box. Of these, then, I'm seeing overlap of DBM and PetTracker with Toetag's original comment. My gut feeling is that it's either PetTracker (this hasn't worked properly for SL) or Reputation Bars (this has been giving me separate issues for years now). Thoughts?

**Comment by jaredbwasserman** [comment]
Thank you for the investigation @halloaloe - I will download Soulshape Journal to look into why the conflict between these two addons is occurring. As for why the issue was occurring late last year, there is a chance it is related to an old version of Drift. I made some updates last November that may be related to the behavior you were seeing, although it would be difficult to confirm.

**Comment by halloaloe** [comment]
After re-enabling all my addons and testing on several characters, I can only conclude the problem is Drift. Whenever Drift is disabled, there's no brown box, just the LUA errors I initially posted in my first comment (and my error sound going off whenever I open my bags). I disabled bags within Drift, clicked Ok, and now my bags "work" with no error sound, but still box upon mousing over anything (minimap, bag icons, spells). Disabled Drift again, bags work, no errors. I don't know what else to do.

**Comment by jaredbwasserman** [comment]
Interesting, thanks for the extra detail. I downloaded Soulshape Journal, and I am able to reproduce the issue. I have an idea of what is causing this, and I am working on a fix.

**Comment by jaredbwasserman** [comment]
@halloaloe I updated the Drift code so the box no longer shows up. Can you download the attached zip file and test the update removes the box for you too? Inside the attached zip file is a Drift folder with the updated code. If you copy the Drift folder and replace the existing folder (most likely located in `C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns`) with this updated one that will update the addon.

[drift-v1.0.21-retail.zip](https://github.com/jaredbwasserman/drift/files/7903305/drift-v1.0.21-retail.zip)

**Comment by Toetag1974** [comment]
I already have this file. Since deleting the add on that was causing the issue with the big brown block, I have had no other issues with Drift. Thank you for finding a solution.

    On Thursday, January 20, 2022, 02:13:59 AM CST, Jared Wasserman ***@***.***> wrote:  
 
 


@halloaloe I updated the Drift code so the box no longer shows up. Can you download the attached zip file and test the update removes the box for you too? Inside the attached zip file is a Drift folder with the updated code. If you copy the Drift folder and replace the existing folder (most likely located in C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns) with this updated one that will update the addon.

drift-v1.0.21-retail.zip

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by halloaloe** [comment]
Apologies, I didn't notice this sooner. Used updated file. Enabled bags, did my checks: all good! No box, no errors, bags where I want them. Enabled SSJ; still no issues. I don't know what you changed, but THANK YOU. I can have my sanity back!

**Comment by jaredbwasserman** [comment]
Thanks for confirming! I just released this fix as part of v1.0.22.
