### ISSUE TITLE
Feature Request - Arena Frames

### ISSUE THREAD

**Issue by JyanseiCoding** [jaredbwasserman/drift#28]
I was wondering if it was possible to add the arena health bars to the list of movable frames. By default, they're quite small and tucked to the side and hard to read in the middle of a hectic match.

There are, of course, arena frame addons I could use, but a lot of them are either outdated or no longer receiving updates.

Thank you for all your hard work!

**Comment by jaredbwasserman** [comment]
Hi @JyanseiCoding - sure I will look into it! Do you mean the ones on the right-hand side under the Minimap?

![InkedWoWScrnShot_030722_231901_LI](https://user-images.githubusercontent.com/5832654/157192031-62f9cbe0-26e9-4991-8250-9c8ee2fd3fa6.jpg)

**Comment by jaredbwasserman** [comment]
Also, are you playing on retail or BC classic?

**Comment by JyanseiCoding** [comment]
Yep! Those are the ones.

My apologies for not specifying. I'm on retail.

**Comment by jaredbwasserman** [comment]
Hi @JyanseiCoding - I got a solution working and could use your help to test it! This ended up being a bit tricky, and I was not able to get targeting to work while moving the Arena Frames is enabled. It will be possible to move and scale the Arena Frames, but if you try to click on one of the frames in order to target an enemy, it will not work.

Can you do the following:
1. Replace the contents of `C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Drift` (or wherever you have WoW installed) with the contents of the attached zip folder ( [drift-v1.0.24-retail.zip](https://github.com/jaredbwasserman/drift/files/8237070/drift-v1.0.24-retail.zip) ) in order to apply the update.
2. Go into Interface -> Addons -> Drift and check the "Arena" checkbox to enable Arena Frames.
![InkedWoWScrnShot_031122_203510_LI](https://user-images.githubusercontent.com/5832654/158003844-e2432f6a-cb69-4822-a1fd-8196f906c838.jpg)

Once the Arena Frames are enabled, when you go into an arena match, it should be possible to drag the frames around and scale them. Please let me know if this works for you. Thanks!

**Comment by JyanseiCoding** [comment]
Just installed the update, and tried it out in a skirmish. Everything's working perfectly, aside from click-targeting, but it's not at all an issue. I mostly just wanted to be able to resize and adjust it for easier visual feedback, and the update achieves that perfectly!

Thank you so much Sir @jaredbwasserman ! And my apologies for the late response.

**Comment by jaredbwasserman** [comment]
Great, thanks for confirming @JyanseiCoding ! I just released this update as part of Drift `v1.0.25`.
